### ISSUE TITLE
API keys visible, remove & regenerate

### ISSUE THREAD

**Issue by gbroiles** [JaniniRami07/Facebook-Hunter#1]
See lines 44, 46, 58 in lib/token.py

**Comment by JaniniRami07** [comment]
The API secret and API key are meant to be public and it is originally generated by [xHak9x FBI ](https://github.com/xHak9x/fbi)project, And there will be no security concerns as long as you keep your token.cache file private as it will contain you access token.

**Comment by JaniniRami07** [comment]
The API secret and API key are meant to be public and there are no security concerns about it as long as you keep you generated facebook_token.cache private as it contains your access token.
